### ISSUE TITLE
sql to prime a Docker image

### ISSUE THREAD

**Issue by kaihendry** [skeema/skeema#103]
Background: https://twitter.com/kaihendry/status/1172014672666451968

I'm in the habit of using [Docker hub's mysql image](https://hub.docker.com/_/mysql)'s `/docker-entrypoint-initdb.d/` volume path to prime a test database.

I tried it with schema [output of bugzilla](https://github.com/unee-t/skeema-experiment/tree/master/bugzilla):

```
      db:
          image: mysql:5.7
          ports:
              - 3306:3306
          environment:
              MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
              MYSQL_DATABASE: ${MYSQL_DATABASE}
              MYSQL_USER: ${MYSQL_USER}
              MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          volumes:
              - /home/hendry/unee-t/skeema/bugzilla/:/docker-entrypoint-initdb.d/
```

 and I hit **ERROR 1215 (HY000) at line 1: Cannot add foreign key constraint** which could well be another foreign key issue, similar to that of https://github.com/skeema/skeema/issues/102

Bit puzzled that when I do a [restore](https://github.com/unee-t/bugzilla-customisation/blob/master/backup/restore.sh) of a lump .sql backup, it appears to work. But when working without the data (i.e. just the schema), I run into issues. Could well be because of Bugzilla's usage of foreign keys.
