### ISSUE TITLE
Skeema unable to access DB for diffs in container using Github Actions

### ISSUE THREAD

**Issue by fayzaan** [skeema/skeema#208]
Hi,

I am trying to use Skeema to do diffs whenever a Pull Request is created so that we can identify Database changes and manually run the schema change queries. We're using Github and would like to use Github Actions to trigger a job to compare current schema to the one in the pull request, if diffs exist then we want a comment to show the output from Skeema.

I tried using Ubuntu image with mysql5.7 but it seems Skeema is unable to connect to the mysql db instance running in the container or its looking in the wrong place for existing schema when trying to run `push` or `diff` commands. I am able to run manual queries using the same password/username.

Can someone help me understand why Skeema cannot connect to the DB? I did try passing in host using `-h` flag but it is not supported by the `push` or `diff` commands. 

errors when attempting `push` command:
```Run skeema push test -p****-uroot
2023-03-1[4](7744750621#step:10:5) 16:41:40 [WARN]  Skipping /home/runner/work/db_schema_workflow/db_schema_workflow/schemas/test: no host defined for environment "test"
2023-03-14 16:41:40 [INFO]  Pushing changes from /home/runner/work/db_schema_workflow/db_schema_workflow/127.0.0.1:3306/test/*.sql to 127.0.0.1:3306 test
2023-03-14 1[6]
(7744750621#step:10:7):41:40 [INFO]  127.0.0.1:3306 test: No differences found
```

errors attempting `diff` command:
```
Run echo "SQL_OUTPUT=$(skeema diff test -p**** -uroot)" >> $GITHUB_ENV
2023-03-1[4](7744750621#step:11:5) 16:41:40 [WARN]  Skipping /home/runner/work/db_schema_workflow/db_schema_workflow/schemas/test: no host defined for environment "test"
2023-03-14 16:41:40 [INFO]  Generating diff of 127.0.0.1:3306 test vs /home/runner/work/db_schema_workflow/db_schema_workflow/127.0.0.1:3306/test/*.sql
2023-03-14 1[6](7744750621#step:11:7):41:40 [INFO]  127.0.0.1:3306 test: No differences found
```

workflow.yaml
```
name: Schema Differ
on:
  pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7.41
        env:
          MYSQL_ROOT_PASSWORD: ****
          MYSQL_DATABASE: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: set up MySQL
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE test;' -uroot -p****
          mysql -e 'SHOW DATABASES;' -uroot -p****
          mysql -e 'CREATE TABLE clients (id VARCHAR(255) NOT NULL PRIMARY KEY);' -uroot -p**** test
          mysql -e "INSERT INTO clients (id) VALUES('18c8b291-67f4-4a5b-16e3-e246568d08e1');" -uroot -p**** test
      - name: make tmp dir
        run: mkdir tmp && touch tmp/mysql.sock
      - name: Download Skeema
        run: curl -LO https://github.com/skeema/skeema/releases/latest/download/skeema_amd64.deb
      - name: Install Skeema
        run: sudo apt install ./skeema_amd64.deb
      - name: Checkout Main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Populate container's MySQL with existing Schema
        run: skeema push test -p**** -uroot
      - name: Compare Schema differences between main and Pull Request
        run: |
          echo "SQL_OUTPUT=$(skeema diff test -p**** -uroot)" >> $GITHUB_ENV
        id: diff_output
      - name: Add comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: process.env.SQL_OUTPUT
            })
```
